uploads = []

[[generated]]
id = "gwlzxbL_M3_G41G-M7-9l"
uri = "file://Game/Images/snake.png"
type = "image"
title = "cartoon snake enemy sprite"

[[generated]]
id = "eWUqfJ3KHS5RrW8rA3dYo"
uri = "file://Game/Images/monkey.png"
type = "image"
title = "generated_image"

[[generated]]
id = "S1Te2ttS4PSzZBpEjxU6o"
uri = "file://Game/Images/lion.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "9A9KBrivuvtGtctgqwmBm"
uri = "file://Game/Sounds/spooky_peaceful.wav"
type = "audio"
title = "Spooky Peaceful (latest level music)"

[[outputs]]
id = "bdDIz78iiXIwiJidJYl-j"
uri = "file://Game/Sounds/boss_spooky.wav"
type = "audio"
title = "Boss song (softer)"

[[outputs]]
id = "zUwrRafZkX9Ov2U7Ct7cJ"
uri = "file://Game/Sounds/final_push.wav"
type = "audio"
title = "Final Push (last level music before boss)"
